### ISSUE TITLE
Error installing on Mac OSx

### ISSUE THREAD

**Issue by joaocc** [DominikGuzei/xsl-transform#1]
Hi,
`npm install -g xsl-transform` gives the following error:

```
|
> node_xslt@0.1.9 preinstall /Users/myself/.node/lib/node_modules/xsl-transform/node_modules/node_xslt
> node-gyp rebuild

  CXX(target) Release/obj.target/node_xslt/node_xslt.o
../node_xslt.cc:18:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope handlescope;
                ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node_xslt.cc:19:30: error: member reference type 'Persistent<v8::Value>' is not a pointer; maybe you meant to use '.'?
    Local<Object> obj = value->ToObject();
                        ~~~~~^~
                             .
../node_xslt.cc:19:32: error: no member named 'ToObject' in 'v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >'
    Local<Object> obj = value->ToObject();
                        ~~~~~  ^
../node_xslt.cc:26:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope handlescope;
                ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node_xslt.cc:27:30: error: member reference type 'Persistent<v8::Value>' is not a pointer; maybe you meant to use '.'?
    Local<Object> obj = value->ToObject();
                        ~~~~~^~
                             .
../node_xslt.cc:27:32: error: no member named 'ToObject' in 'v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >'
    Local<Object> obj = value->ToObject();
                        ~~~~~  ^
../node_xslt.cc:33:1: error: calling a protected constructor of class 'v8::HandleScope'
OBJECT(jsXmlDoc, 1, xmlDocPtr doc)
^
../macros.h:133:21: note: expanded from macro 'OBJECT'
    v8::HandleScope handlescope;\
                    ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node_xslt.cc:33:1: error: too few arguments to function call, at least argument 'isolate' must be specified
OBJECT(jsXmlDoc, 1, xmlDocPtr doc)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../macros.h:134:79: note: expanded from macro 'OBJECT'
    v8::Handle<v8::FunctionTemplate>   __class__  = v8::FunctionTemplate::New();\
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:3: note: 'New' declared here
  static Local<FunctionTemplate> New(
  ^
../node_xslt.cc:34:5: error: too few arguments to function call, expected 2, have 1
    INTERNAL(0, doc)
    ^~~~~~~~~~~~~~~~
../macros.h:156:61: note: expanded from macro 'INTERNAL'
    self->SetInternalField(i, v8::External::New((void*)value));
                              ~~~~~~~~~~~~~~~~~             ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:3154:3: note: 'New' declared here
  static Local<External> New(Isolate* isolate, void* value);
  ^
../node_xslt.cc:35:5: error: too few arguments to function call, expected 2, have 1
    OBJ_DESTRUCTOR(&jsXmlDocCleanup)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_xslt.cc:12:89: note: expanded from macro 'OBJ_DESTRUCTOR'
#define OBJ_DESTRUCTOR(d) Persistent<Object> _weak_handle = Persistent<Object>::New(self); \
                                                            ~~~~~~~~~~~~~~~~~~~~~~~     ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:572:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8config.h:289:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../node_xslt.cc:35:5: error: 'New' is a private member of 'v8::PersistentBase<v8::Object>'
    OBJ_DESTRUCTOR(&jsXmlDocCleanup)
    ^
../node_xslt.cc:12:81: note: expanded from macro 'OBJ_DESTRUCTOR'
#define OBJ_DESTRUCTOR(d) Persistent<Object> _weak_handle = Persistent<Object>::New(self); \
                                                                                ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../node_xslt.cc:35:5: error: no member named 'MakeWeak' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    OBJ_DESTRUCTOR(&jsXmlDocCleanup)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_xslt.cc:13:40: note: expanded from macro 'OBJ_DESTRUCTOR'
                          _weak_handle.MakeWeak(NULL, d);
                          ~~~~~~~~~~~~ ^
../node_xslt.cc:36:5: error: no member named 'Close' in 'v8::HandleScope'
    RETURN_SCOPED(self);
    ^~~~~~~~~~~~~~~~~~~
../macros.h:112:52: note: expanded from macro 'RETURN_SCOPED'
#define RETURN_SCOPED(x)        return handlescope.Close(x)
                                       ~~~~~~~~~~~ ^
../node_xslt.cc:39:1: error: calling a protected constructor of class 'v8::HandleScope'
OBJECT(jsXsltStylesheet, 1, xsltStylesheetPtr style)
^
../macros.h:133:21: note: expanded from macro 'OBJECT'
    v8::HandleScope handlescope;\
                    ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../node_xslt.cc:39:1: error: too few arguments to function call, at least argument 'isolate' must be specified
OBJECT(jsXsltStylesheet, 1, xsltStylesheetPtr style)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../macros.h:134:79: note: expanded from macro 'OBJECT'
    v8::Handle<v8::FunctionTemplate>   __class__  = v8::FunctionTemplate::New();\
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:3455:3: note: 'New' declared here
  static Local<FunctionTemplate> New(
  ^
../node_xslt.cc:40:5: error: too few arguments to function call, expected 2, have 1
    INTERNAL(0, style)
    ^~~~~~~~~~~~~~~~~~
../macros.h:156:61: note: expanded from macro 'INTERNAL'
    self->SetInternalField(i, v8::External::New((void*)value));
                              ~~~~~~~~~~~~~~~~~             ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:3154:3: note: 'New' declared here
  static Local<External> New(Isolate* isolate, void* value);
  ^
../node_xslt.cc:41:5: error: too few arguments to function call, expected 2, have 1
    OBJ_DESTRUCTOR(&jsXsltStylesheetCleanup)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_xslt.cc:12:89: note: expanded from macro 'OBJ_DESTRUCTOR'
#define OBJ_DESTRUCTOR(d) Persistent<Object> _weak_handle = Persistent<Object>::New(self); \
                                                            ~~~~~~~~~~~~~~~~~~~~~~~     ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:572:3: note: 'New' declared here
  V8_INLINE static T* New(Isolate* isolate, T* that);
  ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8config.h:289:20: note: expanded from macro 'V8_INLINE'
# define V8_INLINE inline __attribute__((always_inline))
                   ^
../node_xslt.cc:41:5: error: 'New' is a private member of 'v8::PersistentBase<v8::Object>'
    OBJ_DESTRUCTOR(&jsXsltStylesheetCleanup)
    ^
../node_xslt.cc:12:81: note: expanded from macro 'OBJ_DESTRUCTOR'
#define OBJ_DESTRUCTOR(d) Persistent<Object> _weak_handle = Persistent<Object>::New(self); \
                                                                                ^
/Users/myself/.node-gyp/0.12.2/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../node_xslt.cc:41:5: error: no member named 'MakeWeak' in 'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    OBJ_DESTRUCTOR(&jsXsltStylesheetCleanup)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_xslt.cc:13:40: note: expanded from macro 'OBJ_DESTRUCTOR'
                          _weak_handle.MakeWeak(NULL, d);
                          ~~~~~~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_xslt/node_xslt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/nvm/0.24.1/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/Cellar/nvm/0.24.1/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /users/myself/.node/lib/node_modules/xsl-transform/node_modules/node_xslt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/Cellar/nvm/0.24.1/versions/node/v0.12.2/bin/npm" "install" "-g" "xsl-transform"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code ELIFECYCLE

npm ERR! node_xslt@0.1.9 preinstall: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node_xslt@0.1.9 preinstall script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node_xslt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node_xslt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /users/myself/Dropbox (Corp)/scripts/npm-debug.log
```

**Comment by DominikGuzei** [comment]
Hey @joaocc!
This seems to be a problem with the  `node_xslt` package dependencies, please conduct a google search, I found other places where people already discussed possible solutions, e.g:
https://github.com/prerender/prerender/issues/109

This thread seems to indicate that your installed python version and / or node.js version could cause the problem.

**Comment by roosnic1** [comment]
Hi @joaocc any news on this issue? Can we expect a solution in the near future?

**Comment by joaocc** [comment]
Hi. We used an alternative transform engine and are no longer developing this.  Thx
